   /* agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }* /
        stage('SCM Checkout') {
               git 'https://github.com/harishvarma44/Jfrog1.git'
            }

        stage('Build')
            steps {
                // Get maven home path
                   def mvnHome =  tool name: 'mvn3.3.9', type: 'maven'
                   sh "${mvnHome}/bin/mvn package"
            }
 
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
